### ISSUE TITLE
Make 1.2 release 

### ISSUE THREAD

**Issue by abalkin** [kparc/k#4]
# TODO

* [x] migrate 3 outstanding issues from legacy repo milestones into 1.2 public release milestone
* [x] archive legacy repository
* [x] fix issues (incl CI)
* [x] make github release

**Comment by k-olya** [comment]
solved in #15

**Comment by k-olya** [comment]
1.2 is out, ci is not complete yet
