### ISSUE TITLE
fix npm i

### ISSUE THREAD

**Issue by k-olya** [kparc/k#7]
`get.sh` has to run before node installs dependencies (because we need k binary in the directory by that time). however, `get.sh` depends on a minified version of `get.js` and, consequently, has uglify-es as a dependency.

`git clone && npm i` will fail

i suggest that `get.sh` would fall back from `get.min.js` to `get.js`

# TODO

* [x] review https://docs.npmjs.com/misc/scripts
* [x] ensure that `npm i github:kparc/k -g` works
* [x] move `rm bin/k` to "prepack"

**Comment by k-olya** [comment]
solved in #15
